//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2



use sea_orm :: entity :: prelude :: * ; use super :: sea_orm_active_enums :: FileType ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel)] # [sea_orm (table_name = "files")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub cdn_uri : String , pub r#type : FileType , }

# [derive (Copy , Clone , Debug , EnumIter)] pub enum Relation { }

impl RelationTrait for Relation { fn def (& self) -> RelationDef { panic ! ("No RelationDef") } }

impl ActiveModelBehavior for ActiveModel { }